package com.example.stephentakyi.realmproject;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

/**
 * Created by Stephen Takyi on 2/24/2017.
 */

public class User extends RealmObject {

    public String          name;
    public int             age;

    @PrimaryKey
    public String          id;

    @Ignore
    public int             sessionId;



    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public int    getAge() { return age; }
    public void   setAge(int age) { this.age = age; }
    public int    getSessionId() { return sessionId; }
    public void   setSessionId(int sessionId) { this.sessionId = sessionId; }

}
